before_install: sudo apt-get install libicu-dev libmagic-dev -y

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install PyYAML"
  - "pip install six"
  - "pip install Pygments>=2.5.2"
  - "pip install pygments-github-lexers>=0.0.3"
  - "pip install charlockholmes"
  - "pip install mime>=0.0.3"
  - "pip install scanner>=0.0.4"

branches:
  only:
    - master

script:
  - "cd tests"
  - "python run.py"
